### PR TITLE
Make `ribAddFn` support >1 address family.

### PR DESCRIPTION
**Pull request by robshakir**
```
commit 2001e03fc68c61a478c1639efb851e3fa4b867f7
Author: Rob Shakir <robjs@google.com>
Date:   Sat Sep 2 00:36:02 2023 +0000

    Change signature of ribAddFn to support non-IPv4.
    
     * (M) gribi/gribi.go
      - Adopt an upstream change from gribigo to make the function
        called after an entry is found to be resolvable support more
        than just IPv4. This is required to support other address families
        in lemming.
```

### CODE REVIEW

**Comment by robshakir** [comment]
Upstream PR needs to be submitted before tests will pass.

**Review by DanG100 — APPROVED** [review]

**Comment by DanG100** [comment]
You could get this to build by `go get`ting the sha of the commit in the gribigo branch with the change.

**Comment by robshakir** [comment]
Thanks -- good idea.

It looks like there's an issue with the `gobgp` imports that are being used:

```
[18:26] robjs@aardvark:github.com/openconfig/lemming   gribigochg ✔                                                                                                                                                                                                                 12d ⚑  
▶ go mod tidy
go: downloading cloud.google.com/go/cloudbuild v1.13.0
go: downloading cloud.google.com/go/longrunning v0.5.1
go: finding module for package github.com/wenovus/gobgp/v3/pkg/table
go: finding module for package github.com/wenovus/gobgp/v3/pkg/bgpconfig
go: github.com/openconfig/lemming/bgp imports
	github.com/wenovus/gobgp/v3/pkg/bgpconfig: module github.com/wenovus/gobgp/v3@latest found (v3.0.0-20230816063421-5f01c74a5b06), but does not contain package github.com/wenovus/gobgp/v3/pkg/bgpconfig
go: github.com/openconfig/lemming/bgp imports
	github.com/wenovus/gobgp/v3/pkg/table: module github.com/wenovus/gobgp/v3@latest found (v3.0.0-20230816063421-5f01c74a5b06), but does not contain package github.com/wenovus/gobgp/v3/pkg/table
```

Should we be updating the `wenovus/gobgp` fork to use an updated module name to make this work as expected?

**Comment by DanG100** [comment]
worked for me, I pushed the changes to your branch

**Comment by robshakir** [comment]
Ah, thanks! Not sure what went wrong there.

**Pull request merged**
